name: Nuro case study on the Cloud
location:
  byon:
    user: ubuntu
    privateKeyFile: ~/seaclouds.pem
    hosts:
    - 52.31.1.222
    - 52.30.247.159

services:

- serviceType: org.apache.brooklyn.entity.software.base.VanillaSoftwareProcess
  name: DC+PHP
  id: dc+php
  brooklyn.config:
    launch.command: "true"
    stop.command: "true"
    checkRunning.command: "true"
    children.startable.mode: background_late
  brooklyn.children:
  - serviceType: brooklyn.entity.basic.VanillaSoftwareProcess
    name: PHP
    id: php
    provisioning.properties:
      stopIptables: true

    launch.command: |
      sudo apt-get update
      sudo apt-get -y install apache2 apache2-utils php5 php5-mysql libaio1 unzip 
      wget -O nurogames-seaclouds-casestudy-php.tgz "http://${USER}:${PASSWORD}@seaclouds-dev.nurogames.com/nuro-casestudy/versions/${VERSION}"
      sudo tar --directory=/var/www/html -xzf nurogames-seaclouds-casestudy-php.tgz
      sudo chmod -R 777 /var/www/html/nuro-casestudy
      cp '/var/www/html/nuro-casestudy/config/config_template.php' '/var/www/html/nuro-casestudy/config/config.php'
      sed -i "s/%host%/$HOST/" /var/www/html/nuro-casestudy/config/config.php
      sed -i "s/%database%/$DB_NAME/" /var/www/html/nuro-casestudy/config/config.php
      sed -i "s/%user%/$DB_USER/" /var/www/html/nuro-casestudy/config/config.php
      sed -i "s/%password%/$DB_PASSWORD/" /var/www/html/nuro-casestudy/config/config.php
      sudo service apache2 restart

    checkRunning.command: |
      sudo service apache2 status

    stop.command: |
      sudo service apache2 stop

    env:
      USER: seaclouds
      PASSWORD: preview
      VERSION: D6.3.2/nurogames-seaclouds-casestudy-php-D6.3.2v0.1_20150921_1543CET.tgz
      HOST: $brooklyn:component("db").attributeWhenReady("host.name")
      DB_NAME: "database1"
      DB_USER: "brooklyn"
      DB_PASSWORD: "br00k11n"

  - serviceType: brooklyn.entity.basic.VanillaSoftwareProcess
    name: DC
    id: dc
    launch.command: |
      sudo apt-get update
      sudo apt-get install -y openjdk-7-jre
      wget -O nuro-data-collector.jar https://www.dropbox.com/s/db6o4f4k5cgv16y/nuro-data-collector-0.8.0-SNAPSHOT-jar-with-dependencies.jar
      wget -O config.properties https://www.dropbox.com/s/pp22gk2g8o5gzte/config.properties
      nohup java -jar nuro-data-collector.jar ./config.properties > nuroDc.log 2>&1 &
      echo $! > $PID_FILE

    install.latch: $brooklyn:component("php").attributeWhenReady("service.isUp")

- serviceType: org.apache.brooklyn.entity.database.mysql.MySqlNode
  id: db
  name: Nuro DB
  brooklyn.config:
    datastore.creation.script.url: ./create.sql